//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_medicine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int Id_visited { get; set; }
        public int Id_patient { get; set; }
        public int Id_specialist { get; set; }
        public System.DateTime Data_of_visit { get; set; }
        public string Conclusion { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Specialist Specialist { get; set; }
    }
}
